// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fourfit.sistema_gestao.Context;

#nullable disable

namespace fourfit.sistema_gestao.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240713222157_TBunica")]
    partial class TBunica
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Account.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PrimeiroNome")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SobreNome")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Alunos.AvaliacaoFisica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Abdomen")
                        .IsRequired()
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("AlunosId")
                        .HasColumnType("int");

                    b.Property<decimal?>("AntebracoD")
                        .IsRequired()
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("AntebracoE")
                        .IsRequired()
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("BicepsContraidoD")
                        .IsRequired()
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("BicepsContraidoE")
                        .IsRequired()
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("BicepsRelaxadoD")
                        .IsRequired()
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("BicepsRelaxadoE")
                        .IsRequired()
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Cintura")
                        .IsRequired()
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Costa")
                        .IsRequired()
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("CoxaD")
                        .IsRequired()
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("CoxaE")
                        .IsRequired()
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("date");

                    b.Property<decimal?>("GorduraVisceral")
                        .IsRequired()
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("Idade")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("IdadeCorporal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Imc")
                        .IsRequired()
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("MassaMagra")
                        .IsRequired()
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("PanturrilhaD")
                        .IsRequired()
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("PanturrilhaE")
                        .IsRequired()
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Peitoral")
                        .IsRequired()
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PercentualGordura")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Quadril")
                        .IsRequired()
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("TaxaMetabolica")
                        .IsRequired()
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("AlunosId");

                    b.ToTable("AvaliacaoFisica", (string)null);
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Alunos.Checkins", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunosId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCheckin")
                        .HasColumnType("date");

                    b.Property<int>("HorariosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlunosId");

                    b.HasIndex("HorariosId");

                    b.ToTable("Checkins", (string)null);
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Alunos.EntidadeAlunos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNacimento")
                        .HasColumnType("date");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(7)");

                    b.Property<int?>("TipoPlanoId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TipoPlanoId");

                    b.HasIndex("UserId");

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Alunos.Horarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("LimiteAlunos")
                        .HasColumnType("int");

                    b.Property<int>("ModalidadesId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessoresId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModalidadesId");

                    b.HasIndex("ProfessoresId");

                    b.ToTable("Horarios", (string)null);
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Alunos.Mensalidades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunosId")
                        .HasColumnType("int");

                    b.Property<int>("ContasBancariasId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataInicialPlano")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataPagamento")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("MesReferente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PagamentosId")
                        .HasColumnType("int");

                    b.Property<int>("PlanoId")
                        .HasColumnType("int");

                    b.Property<string>("StatusPagamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ValorMatricula")
                        .IsRequired()
                        .HasColumnType(" decimal(18, 2)");

                    b.Property<string>("ValorMensalidade")
                        .IsRequired()
                        .HasColumnType(" varchar(12)");

                    b.HasKey("Id");

                    b.HasIndex("AlunosId");

                    b.HasIndex("ContasBancariasId");

                    b.HasIndex("PagamentosId");

                    b.HasIndex("PlanoId");

                    b.ToTable("Mensalidades", (string)null);
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Alunos.Modalidades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermiteCheckin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Modalidades");
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Alunos.TipoPlano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescTipoPlano")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoPlano");
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Financas.ContasBancarias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bancos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ContasBancarias");
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Financas.Despesas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("Pagamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoPagamentoId")
                        .HasColumnType("int");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TipoPagamentoId");

                    b.ToTable("Despesas", (string)null);
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Financas.Investimentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("Pagamento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoPagamentoId")
                        .HasColumnType("int");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TipoPagamentoId");

                    b.ToTable("Investimentos", (string)null);
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Financas.TipoPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TipoPagamentoPcId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoPagamentoPcId");

                    b.ToTable("TipoPagamento");
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Financas.TipoPagamentoPc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoPagamentoPc");
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Fornecedor.Fornecedores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasColumnType("varchar(18)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NomeFornecedor")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Fornecedores", (string)null);
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Profission.EntidadeColaboradores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Cpf")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataNacimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Colaboradores", (string)null);
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Profission.EntidadeProfessores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Cpf")
                        .HasColumnType("bigint");

                    b.Property<string>("Cref")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataNacimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Professores", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("fourfit.sistema_gestao.Domain.Entities.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("fourfit.sistema_gestao.Domain.Entities.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fourfit.sistema_gestao.Domain.Entities.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("fourfit.sistema_gestao.Domain.Entities.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Alunos.AvaliacaoFisica", b =>
                {
                    b.HasOne("fourfit.sistema_gestao.Domain.Entities.Alunos.EntidadeAlunos", "Alunos")
                        .WithMany("AvaliacoesFisicas")
                        .HasForeignKey("AlunosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Alunos.Checkins", b =>
                {
                    b.HasOne("fourfit.sistema_gestao.Domain.Entities.Alunos.EntidadeAlunos", "Alunos")
                        .WithMany("Checkins")
                        .HasForeignKey("AlunosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fourfit.sistema_gestao.Domain.Entities.Alunos.Horarios", "Horarios")
                        .WithMany("Checkins")
                        .HasForeignKey("HorariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alunos");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Alunos.EntidadeAlunos", b =>
                {
                    b.HasOne("fourfit.sistema_gestao.Domain.Entities.Alunos.TipoPlano", null)
                        .WithMany("EntidadeAlunos")
                        .HasForeignKey("TipoPlanoId");

                    b.HasOne("fourfit.sistema_gestao.Domain.Entities.Account.User", "User")
                        .WithMany("Alunos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Alunos.Horarios", b =>
                {
                    b.HasOne("fourfit.sistema_gestao.Domain.Entities.Alunos.Modalidades", "Modalidades")
                        .WithMany("Horarios")
                        .HasForeignKey("ModalidadesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fourfit.sistema_gestao.Domain.Entities.Profission.EntidadeProfessores", "Professores")
                        .WithMany("Horarios")
                        .HasForeignKey("ProfessoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modalidades");

                    b.Navigation("Professores");
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Alunos.Mensalidades", b =>
                {
                    b.HasOne("fourfit.sistema_gestao.Domain.Entities.Alunos.EntidadeAlunos", "Alunos")
                        .WithMany("Mensalidades")
                        .HasForeignKey("AlunosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fourfit.sistema_gestao.Domain.Entities.Financas.ContasBancarias", "ContasBancarias")
                        .WithMany("Mensalidades")
                        .HasForeignKey("ContasBancariasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fourfit.sistema_gestao.Domain.Entities.Financas.TipoPagamento", "Pagamentos")
                        .WithMany("Mensalidades")
                        .HasForeignKey("PagamentosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fourfit.sistema_gestao.Domain.Entities.Alunos.TipoPlano", "Planos")
                        .WithMany("Mensalidades")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alunos");

                    b.Navigation("ContasBancarias");

                    b.Navigation("Pagamentos");

                    b.Navigation("Planos");
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Financas.Despesas", b =>
                {
                    b.HasOne("fourfit.sistema_gestao.Domain.Entities.Financas.TipoPagamento", "TipoPagamento")
                        .WithMany()
                        .HasForeignKey("TipoPagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoPagamento");
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Financas.Investimentos", b =>
                {
                    b.HasOne("fourfit.sistema_gestao.Domain.Entities.Financas.TipoPagamento", "TipoPagamento")
                        .WithMany()
                        .HasForeignKey("TipoPagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoPagamento");
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Financas.TipoPagamento", b =>
                {
                    b.HasOne("fourfit.sistema_gestao.Domain.Entities.Financas.TipoPagamentoPc", "TipoPagamentoPc")
                        .WithMany("TipoPagamento")
                        .HasForeignKey("TipoPagamentoPcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoPagamentoPc");
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Profission.EntidadeColaboradores", b =>
                {
                    b.HasOne("fourfit.sistema_gestao.Domain.Entities.Account.User", "User")
                        .WithMany("colaboradores")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Profission.EntidadeProfessores", b =>
                {
                    b.HasOne("fourfit.sistema_gestao.Domain.Entities.Account.User", "User")
                        .WithMany("Professores")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Account.User", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Professores");

                    b.Navigation("colaboradores");
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Alunos.EntidadeAlunos", b =>
                {
                    b.Navigation("AvaliacoesFisicas");

                    b.Navigation("Checkins");

                    b.Navigation("Mensalidades");
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Alunos.Horarios", b =>
                {
                    b.Navigation("Checkins");
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Alunos.Modalidades", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Alunos.TipoPlano", b =>
                {
                    b.Navigation("EntidadeAlunos");

                    b.Navigation("Mensalidades");
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Financas.ContasBancarias", b =>
                {
                    b.Navigation("Mensalidades");
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Financas.TipoPagamento", b =>
                {
                    b.Navigation("Mensalidades");
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Financas.TipoPagamentoPc", b =>
                {
                    b.Navigation("TipoPagamento");
                });

            modelBuilder.Entity("fourfit.sistema_gestao.Domain.Entities.Profission.EntidadeProfessores", b =>
                {
                    b.Navigation("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
